INSERT INTO `reviews` (
        `id`,
        `order_id`,
        `user_id`,
        `shop_id`,
        `product_id`,
        `variation_option_id`,
        `comment`,
        `rating`,
        `photos`,
        `deleted_at`,
        `created_at`,
        `updated_at`
    )
VALUES (
        1,
        15,
        2,
        6,
        33,
        NULL,
        'Exceptional digital product! Its user-friendly interface simplifies tasks, offering robust features that enhance productivity. The customer support is stellar, promptly addressing queries. It is been a game-changer, streamlining workflows effectively. Highly recommended for anyone seeking efficiency and innovation in their digital endeavors.',
        5,
        '[]',
        NULL,
        '2023-11-17 06:35:58',
        '2023-11-17 06:35:58'
    ),
    (
        2,
        17,
        2,
        7,
        27,
        NULL,
        'Exceptional digital product! The user-friendly interface ensures a seamless experience. Robust features meet all needs effortlessly. It enhances productivity and simplifies tasks, making it a must-have tool. The responsive support team adds immense value. Truly a game-changer in the digital landscape, and highly recommended for its efficiency and innovation.',
        4,
        '[]',
        NULL,
        '2023-11-17 12:08:43',
        '2023-11-17 12:08:43'
    ),
    (
        3,
        17,
        2,
        7,
        34,
        NULL,
        'Its intuitive interface and customizable features make organizing my tasks a breeze. The sleek design enhances user experience, and cloud synchronization ensures accessibility across devices. A game-changer for productivity, this digital product is a must-have for anyone seeking efficient and organized planning.',
        3,
        '[]',
        NULL,
        '2023-11-17 12:09:13',
        '2023-11-17 12:09:13'
    ),
    (
        4,
        19,
        2,
        6,
        46,
        NULL,
        'Good Product, but expensive.',
        2,
        '[]',
        NULL,
        '2023-11-17 13:13:37',
        '2023-11-17 13:13:37'
    ),
    (
        5,
        21,
        2,
        1,
        11,
        NULL,
        'Excellent product with a very minimal design. It\'s so user-friendly. Just Loved it.',
        5,
        '[]',
        NULL,
        '2023-11-17 13:14:55',
        '2023-11-17 13:14:55'
    ),
    (
        6,
        23,
        2,
        2,
        42,
        NULL,
        'Amazing product, very helpful and compact.',
        5,
        '[]',
        NULL,
        '2023-11-17 13:16:14',
        '2023-11-17 13:16:14'
    ),
    (
        7,
        25,
        2,
        3,
        43,
        NULL,
        'The design is outstanding. Very nice theme. It\'s very userfriendly and helpful.',
        5,
        '[]',
        NULL,
        '2023-11-17 13:17:40',
        '2023-11-17 13:17:40'
    ),
    (
        8,
        27,
        2,
        4,
        31,
        NULL,
        'The product is way too simple but the features are useful. giving them 3 stars. Please improve the design quality.',
        3,
        '[]',
        NULL,
        '2023-11-17 13:19:31',
        '2023-11-17 13:19:31'
    ),
    (
        9,
        29,
        2,
        5,
        39,
        NULL,
        'Its intuitive interface and customizable features make organizing my tasks a breeze. The sleek design enhances user experience, and cloud synchronization ensures accessibility across devices. A game-changer for productivity, this digital product is a must-have for anyone seeking efficient and organized planning.',
        5,
        '[]',
        NULL,
        '2023-11-17 13:20:58',
        '2023-11-17 13:20:58'
    ),
    (
        10,
        31,
        2,
        8,
        48,
        NULL,
        'The user-friendly interface ensures a seamless experience. Robust features meet all needs effortlessly. It enhances productivity and simplifies tasks, making it a must-have tool. The responsive support team adds immense value. Truly a game-changer in the digital landscape, and highly recommended for its efficiency and innovation.',
        4,
        '[]',
        NULL,
        '2023-11-17 13:21:21',
        '2023-11-17 13:21:21'
    ),
    (
        11,
        33,
        2,
        9,
        20,
        NULL,
        'The product needs to improve. With this price range we expect more advance features.',
        1,
        '[]',
        NULL,
        '2023-11-17 13:22:19',
        '2023-11-17 13:22:19'
    );